# Historic diesel prices
name: download wg gesucht

# Controls when the action will run.
on:
  schedule:
    - cron:  "0 */3 * * *"
  workflow_dispatch:


jobs:

  generate-data:

    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    # Load repo and install R
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@v2

    - name: install libcurl
      run: |
       sudo apt-get install libcurl4-openssl-dev

    # Set-up R
    - name: Install packages
      run: |
        R -e 'install.packages("dplyr")'
        R -e 'install.packages("rvest")'
        R -e 'install.packages("stringr")'
        R -e 'install.packages("tidygeocoder")'
    # Run R script
    - name: Scrape
      run: Rscript _wgGesucht/analysis/testDownload.R

 # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add -A
        git commit -am "data $(date)"
        git push origin main
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions

